name: lite_cart
description: Kitabu Pivot to ecommerce retail

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^0.3.9
  font_awesome_flutter:
  curved_navigation_bar: 

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    # splash assets
    - assets/logo.jpg
    # onboarding assets
    - assets/images/slider_1.png
    - assets/images/slider_2.png
    - assets/images/slider_3.png
    # profile assets
    - assets/profile/logo.png
    - assets/profile/powered_by.png
    - assets/profile/email_icon.png
    - assets/profile/password_icon.png
    - assets/profile/user_icon.png
    - assets/profile/as.png
    # Home assets
    - assets/home/jacket.png
    - assets/home/shoe_thumb_1.png
    - assets/home/shoe_thumb_2.png
    - assets/home/shoe_thumb_3.png
    - assets/home/shoe_thumb_4.png
    - assets/home/shoe_thumb_5.png
    - assets/home/shooe_tilt_1.png
    - assets/home/shoe_tilt_2.png
    - assets/home/show_1.png
    - assets/home/small_tilt_shoe_1.png
    - assets/home/small_tilt_shoe_2.png
    - assets/home/small_tilt_shoe_3.png
    - assets/home/user.png
    - assets/home/watch.png
    # SideBar assets
    - assets/sideBar/imgs/cat.png
    - assets/sideBar/imgs/dog.png
    - assets/sideBar/imgs/horse.png
    - assets/sideBar/imgs/parrot.png
    - assets/sideBar/imgs/pet-cat1.png
    - assets/sideBar/imgs/pet-cat2.png
    - assets/sideBar/imgs/rabbit.png

  fonts:
    # onboarding fonts
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    # SideBar assets
    - family: Circular
      fonts:
        - asset: assets/sideBar/fonts/CircularStd-Medium.ttf
        - asset: assets/sideBar/fonts/CircularAir-Light.ttf
          weight: 100
        - asset: assets/sideBar/fonts/CircularStd-Bold.ttf
          weight: 500